
    exports.projectData = [
        { 'TaskID': 1, 'LHS': 'Product Info', 'StartDate': new Date('02/23/2017'), 'qty': '', 'total' : '',
        'unit':'', 'pricePer': '' , 'source':"" },
        { 'TaskID': 2, 'LHS': 'Vendor Name', 'description': '"Nature Made" Fish Oil 1200 mg., 400 Softgels', 'qty': '', 'total' : '',
        'unit':'', 'pricePer': '', 'parentID': 1 , 'source':""  },
        { 'TaskID': 3, 'LHS': 'Costum Name', 'description':'"Nature Made" "Fish Oil" 2400 mg Omega-3 720mg, Total: 200 Servings (for 200 Days), 400 softgels (2 Bottles)', 'qty': '', 'total' : '',
        'unit':'', 'pricePer': '', 'parentID': 1 , 'source':""  },
        { 'TaskID': 4, 'LHS': 'Model', 'description':'', 'qty': '', 'total' : '',
        'unit':'', 'pricePer': '', 'parentID': 1 , 'source':""  },
        { 'TaskID': 8, 'LHS': 'Brand', 'description':'Nature Made', 'qty': '', 'total' : '',
        'unit':'', 'pricePer': '', 'parentID': 1 , 'source':""  },
        { 'TaskID': 4, 'LHS': 'Name', 'description':'Fish Oil', 'qty': '', 'total' : '',
        'unit':'', 'pricePer': '', 'parentID': 1 , 'source':""  },
        { 'TaskID': 4, 'LHS': 'Product Type', 'description':'Fish Oil', 'qty': '', 'total' : '',
        'unit':'', 'pricePer': '', 'parentID': 1 , 'source':""  },
        { 'TaskID': 5, 'LHS': 'Packaging', 'description': '', 'qty': '', 'total' : '',
        'unit':"", 'pricePer': '' , 'source':"URL"  },
        { 'TaskID': 6, 'LHS': 'Bottle', 'description': '2 Bottles (Total)', 'qty': 2, 'total' : 2,
        'unit':"Bottle", 'pricePer': 'price/2', 'parentID': 5 , 'source':""  },
        { 'TaskID': 7, 'LHS': 'Softgel', 'description': '200 Softgels (per Bottle)', 'qty': 200, 'total' : 400,
        'unit':"Softgel", 'pricePer': 'price/400', 'parentID': 5 , 'source':""  },
        { 'TaskID': 20, 'LHS': 'Serving Size', 'description': '', 'qty': '', 'total' : '',
        'unit':"", 'pricePer': '' , 'source':""  },
        { 'TaskID': 22, 'LHS': 'Day', 'description': '200 Days (Total)', 'qty': '', 'total' : '200',
        'unit':"Day", 'pricePer': 'price/200' , 'source':"" , 'parentID': 20 },
        { 'TaskID': 23, 'LHS': 'Serving ', 'description': '1 Servings(per day)', 'qty': 1, 'total' : '200',
        'unit':"Serving", 'pricePer': 'price/200' , 'source':"" ,  'parentID': 22   },
        { 'TaskID': 24, 'LHS': 'Softgel', 'description': '2 Softgel (per serving) ', 'qty': 2, 'total' : '',
        'unit':"Softgel", 'pricePer': '' , 'source':"" ,  'parentID': 23   },
        { 'TaskID': 25, 'LHS': 'Serving Time', 'description': '', 'qty': '', 'total' : '',
        'unit':"", 'pricePer': '' , 'source':"" ,   'parentID': 20  },
        { 'TaskID': 10, 'LHS': 'Price', 'description': '"Fish Oil" 2400 mg Omega-3 720mg, Total: 100 Servings (for 100 Days), 200 softgels (1 Bottle)', 'qty': '', 'total' : 'Breaker',
        'unit':"", 'pricePer': '' , 'source':""  },
        { 'TaskID': 11, 'LHS': 'Amazon (by Amazon)" "Fish Oil" 2400 mg Omega-3 720mg, Total: 100 Servings (for 100 Days), 200 softgels (1 Bottle)', 'description': '$17.85', 'qty': '', 'total' : '15.29',
        'unit':"USD", 'pricePer': '', 'parentID': 10 , 'source':""  },
        { 'TaskID': 12, 'LHS': 'Amazon (by 3rd Party)', 'description': '$13.49', 'qty': '', 'total' : '13.49',
        'unit':"USD", 'pricePer': 'price', 'parentID': 10 , 'source':"URL"  },
    ]; 
	
